routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::resource('api/application', 'ApplicationController');
//Route::resource('api/application/submit', 'ApplicationController@submit');

Auth::routes();
Route::get('/home', 'HomeController@index');

Route::resource('ipoCategories', 'IpoCategoryController');

Route::resource('applicationTypes', 'ApplicationTypeController');

Route::resource('applicationDetails', 'ApplicationDetailController');

Route::resource('applicants', 'ApplicantController');

Route::resource('corporateDetails', 'CorporateDetailController');

Route::resource('applicantDetails', 'ApplicantDetailController');

Route::resource('countries', 'CountryController');

Route::resource('states', 'StateController');

Route::resource('addresses', 'AddressController');

Route::resource('stockBrokerCompanies', 'StockBrokerCompanyController');

Route::resource('stockBrokers', 'StockBrokerController');

Route::resource('banks', 'BankController');

Route::resource('bankDetails', 'BankDetailController');

Route::resource('ipoRequests', 'IpoRequestController');

Route::resource('biddings', 'BiddingController');

Route::resource('ipoTypes', 'IpoTypeController');

Route::resource('partyTypes', 'PartyTypeController');

Route::resource('ipoDetails', 'IpoDetailController');

Route::resource('ipoProcesses', 'IpoProcessController');

Route::resource('allocations', 'AllocationController');

Route::resource('stockBrokerIpos', 'StockBrokerIpoController');

Route::resource('participants', 'ParticipantController');



Route::resource('partyResponses', 'PartyResponseController');

Route::resource('batches', 'BatchController');

Route::resource('batchContents', 'BatchContentController');

Route::resource('applicationApplicants', 'ApplicationApplicantController');







Route::resource('applicationSignatures', 'ApplicationSignatureController');

Route::resource('users', 'UserController');

Route::resource('serviceRequests', 'ServiceRequestController');

Route::resource('issuingHouses', 'IssuingHouseController');

Route::resource('issuingHouseStaffs', 'IssuingHouseStaffController');

Route::resource('registrars', 'RegistrarController');

Route::resource('registrarStaffs', 'RegistrarStaffController');

app/Models/StockBrokerCompany.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="StockBrokerCompany",
 *      required={"name", "phone", "email", "addressID"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="phone",
 *          description="phone",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="email",
 *          description="email",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="addressID",
 *          description="addressID",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class StockBrokerCompany extends Model
{
    use SoftDeletes;

    public $table = 'stock_broker_companies';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'phone',
        'email',
        'addressID'
    ];

    protected $hidden=["created_at","updated_at","deleted_at","application_id","addressID"];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'addressID' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'phone' => 'required',
        'email' => 'required',
        'addressID' => 'required'
    ];

    public function agents(){
//        return $this->hasMany("App\Models\StockBroker","company_id","id");
        return $this->hasManyThrough("App\User","App\Models\StockBroker","company_id","id");
    }

    public function ipos(){
        return $this->hasManyThrough("App\Models\IpoDetail","App\Models\StockBrokerIpo","stock_broker_id","id");
    }

    public function batches(){
        return $this->hasMany("App\Models\Batch","company_id","id");
    }

    public function applications(){
//        return $this->hasMany("App\Models\IpoRequest","stock_broker_id","id");
        return $this->hasManyThrough("App\Models\ApplicationDetail","App\Models\IpoRequest","stock_broker_id","id");
    }
}

app/Http/Controllers/StockBrokerCompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateStockBrokerCompanyRequest;
use App\Http\Requests\UpdateStockBrokerCompanyRequest;
use App\Repositories\StockBrokerCompanyRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class StockBrokerCompanyController extends AppBaseController
{
    /** @var  StockBrokerCompanyRepository */
    private $stockBrokerCompanyRepository;

    public function __construct(StockBrokerCompanyRepository $stockBrokerCompanyRepo)
    {
        $this->stockBrokerCompanyRepository = $stockBrokerCompanyRepo;
    }

    /**
     * Display a listing of the StockBrokerCompany.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->stockBrokerCompanyRepository->pushCriteria(new RequestCriteria($request));
        $stockBrokerCompanies = $this->stockBrokerCompanyRepository->all();

        return view('stock_broker_companies.index')
            ->with('stockBrokerCompanies', $stockBrokerCompanies);
    }

    /**
     * Show the form for creating a new StockBrokerCompany.
     *
     * @return Response
     */
    public function create()
    {
        return view('stock_broker_companies.create');
    }

    /**
     * Store a newly created StockBrokerCompany in storage.
     *
     * @param CreateStockBrokerCompanyRequest $request
     *
     * @return Response
     */
    public function store(CreateStockBrokerCompanyRequest $request)
    {
        $input = $request->all();

        $stockBrokerCompany = $this->stockBrokerCompanyRepository->create($input);

        Flash::success('Stock Broker Company saved successfully.');

        return redirect(route('stockBrokerCompanies.index'));
    }

    /**
     * Display the specified StockBrokerCompany.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $stockBrokerCompany = $this->stockBrokerCompanyRepository->findWithoutFail($id);

        if (empty($stockBrokerCompany)) {
            Flash::error('Stock Broker Company not found');

            return redirect(route('stockBrokerCompanies.index'));
        }

        return view('stock_broker_companies.show')->with('stockBrokerCompany', $stockBrokerCompany);
    }

    /**
     * Show the form for editing the specified StockBrokerCompany.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $stockBrokerCompany = $this->stockBrokerCompanyRepository->findWithoutFail($id);

        if (empty($stockBrokerCompany)) {
            Flash::error('Stock Broker Company not found');

            return redirect(route('stockBrokerCompanies.index'));
        }

        return view('stock_broker_companies.edit')->with('stockBrokerCompany', $stockBrokerCompany);
    }

    /**
     * Update the specified StockBrokerCompany in storage.
     *
     * @param  int              $id
     * @param UpdateStockBrokerCompanyRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateStockBrokerCompanyRequest $request)
    {
        $stockBrokerCompany = $this->stockBrokerCompanyRepository->findWithoutFail($id);

        if (empty($stockBrokerCompany)) {
            Flash::error('Stock Broker Company not found');

            return redirect(route('stockBrokerCompanies.index'));
        }

        $stockBrokerCompany = $this->stockBrokerCompanyRepository->update($request->all(), $id);

        Flash::success('Stock Broker Company updated successfully.');

        return redirect(route('stockBrokerCompanies.index'));
    }

    /**
     * Remove the specified StockBrokerCompany from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $stockBrokerCompany = $this->stockBrokerCompanyRepository->findWithoutFail($id);

        if (empty($stockBrokerCompany)) {
            Flash::error('Stock Broker Company not found');

            return redirect(route('stockBrokerCompanies.index'));
        }

        $this->stockBrokerCompanyRepository->delete($id);

        Flash::success('Stock Broker Company deleted successfully.');

        return redirect(route('stockBrokerCompanies.index'));
    }
}

resources/views/stock_broker_companies/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Stock Broker Company
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'stockBrokerCompanies.store']) !!}

                        @include('stock_broker_companies.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/stock_broker_companies/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Stock Broker Company
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($stockBrokerCompany, ['route' => ['stockBrokerCompanies.update', $stockBrokerCompany->id], 'method' => 'patch']) !!}

                        @include('stock_broker_companies.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/stock_broker_companies/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Addressid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('addressID', 'Addressid:') !!}
    {!! Form::select('addressID', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('stockBrokerCompanies.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/stock_broker_companies/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Stock Broker Companies</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('stockBrokerCompanies.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('stock_broker_companies.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/stock_broker_companies/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Stock Broker Company
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('stock_broker_companies.show_fields')
                    <a href="{!! route('stockBrokerCompanies.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/stock_broker_companies/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $stockBrokerCompany->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $stockBrokerCompany->name !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{!! $stockBrokerCompany->phone !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $stockBrokerCompany->email !!}</p>
</div>

<!-- Addressid Field -->
<div class="form-group">
    {!! Form::label('addressID', 'Addressid:') !!}
    <p>{!! $stockBrokerCompany->addressID !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $stockBrokerCompany->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $stockBrokerCompany->updated_at !!}</p>
</div>

resources/views/stock_broker_companies/table.blade.php
<table class="table table-responsive" id="stockBrokerCompanies-table">
    <thead>
        <tr>
            <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Addressid</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($stockBrokerCompanies as $stockBrokerCompany)
        <tr>
            <td>{!! $stockBrokerCompany->name !!}</td>
            <td>{!! $stockBrokerCompany->phone !!}</td>
            <td>{!! $stockBrokerCompany->email !!}</td>
            <td>{!! $stockBrokerCompany->addressID !!}</td>
            <td>
                {!! Form::open(['route' => ['stockBrokerCompanies.destroy', $stockBrokerCompany->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('stockBrokerCompanies.show', [$stockBrokerCompany->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('stockBrokerCompanies.edit', [$stockBrokerCompany->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>