routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::resource('api/application', 'ApplicationController');
//Route::resource('api/application/submit', 'ApplicationController@submit');

Auth::routes();
Route::get('/home', 'HomeController@index');

Route::resource('ipoCategories', 'IpoCategoryController');

Route::resource('applicationTypes', 'ApplicationTypeController');

Route::resource('applicationDetails', 'ApplicationDetailController');

Route::resource('applicants', 'ApplicantController');

Route::resource('corporateDetails', 'CorporateDetailController');

Route::resource('applicantDetails', 'ApplicantDetailController');

Route::resource('countries', 'CountryController');

Route::resource('states', 'StateController');

Route::resource('addresses', 'AddressController');

Route::resource('stockBrokerCompanies', 'StockBrokerCompanyController');

Route::resource('stockBrokers', 'StockBrokerController');

Route::resource('banks', 'BankController');

Route::resource('bankDetails', 'BankDetailController');

Route::resource('ipoRequests', 'IpoRequestController');

Route::resource('biddings', 'BiddingController');

Route::resource('ipoTypes', 'IpoTypeController');

Route::resource('partyTypes', 'PartyTypeController');

Route::resource('ipoDetails', 'IpoDetailController');

Route::resource('ipoProcesses', 'IpoProcessController');

Route::resource('allocations', 'AllocationController');

Route::resource('stockBrokerIpos', 'StockBrokerIpoController');

Route::resource('participants', 'ParticipantController');



Route::resource('partyResponses', 'PartyResponseController');

Route::resource('batches', 'BatchController');

Route::resource('batchContents', 'BatchContentController');

Route::resource('applicationApplicants', 'ApplicationApplicantController');







Route::resource('applicationSignatures', 'ApplicationSignatureController');

Route::resource('users', 'UserController');

Route::resource('serviceRequests', 'ServiceRequestController');

Route::resource('issuingHouses', 'IssuingHouseController');

Route::resource('issuingHouseStaffs', 'IssuingHouseStaffController');

Route::resource('registrars', 'RegistrarController');

Route::resource('registrarStaffs', 'RegistrarStaffController');

app/Models/BankDetail.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="BankDetail",
 *      required={"bank_id", "applicant_id", "account_name", "account_number", "sort_code", "bvn", "state_id"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="bank_id",
 *          description="bank_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="applicant_id",
 *          description="applicant_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="account_name",
 *          description="account_name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="account_number",
 *          description="account_number",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="sort_code",
 *          description="sort_code",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="bvn",
 *          description="bvn",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="state_id",
 *          description="state_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class BankDetail extends Model
{
    use SoftDeletes;

    public $table = 'bank_details';
    

    protected $dates = ['deleted_at'];


    public $guarded=["deleted_at"];
    protected $hidden=["created_at","updated_at","deleted_at","id","application_id","applicant_id"];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'bank_id' => 'integer',
        'applicant_id' => 'integer',
        'application_id'=>'integer',
        'account_name' => 'string',
        'account_number' => 'string',
        'sort_code' => 'string',
        'bvn' => 'string',
        'state' => 'string',
        'city' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'bank_id' => 'required',
        'applicant_id' => 'required',
        'application_id' => 'required',
        'account_name' => 'required',
        'account_number' => 'required',
        'sort_code' => 'required',
        'bvn' => 'required',
        'state' => 'required',
        'city' => 'required'
    ];

    
}

app/Http/Controllers/BankDetailController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateBankDetailRequest;
use App\Http\Requests\UpdateBankDetailRequest;
use App\Repositories\BankDetailRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class BankDetailController extends AppBaseController
{
    /** @var  BankDetailRepository */
    private $bankDetailRepository;

    public function __construct(BankDetailRepository $bankDetailRepo)
    {
        $this->bankDetailRepository = $bankDetailRepo;
    }

    /**
     * Display a listing of the BankDetail.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->bankDetailRepository->pushCriteria(new RequestCriteria($request));
        $bankDetails = $this->bankDetailRepository->all();

        return view('bank_details.index')
            ->with('bankDetails', $bankDetails);
    }

    /**
     * Show the form for creating a new BankDetail.
     *
     * @return Response
     */
    public function create()
    {
        return view('bank_details.create');
    }

    /**
     * Store a newly created BankDetail in storage.
     *
     * @param CreateBankDetailRequest $request
     *
     * @return Response
     */
    public function store(CreateBankDetailRequest $request)
    {
        $input = $request->all();

        $bankDetail = $this->bankDetailRepository->create($input);

        Flash::success('Bank Detail saved successfully.');

        return redirect(route('bankDetails.index'));
    }

    /**
     * Display the specified BankDetail.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $bankDetail = $this->bankDetailRepository->findWithoutFail($id);

        if (empty($bankDetail)) {
            Flash::error('Bank Detail not found');

            return redirect(route('bankDetails.index'));
        }

        return view('bank_details.show')->with('bankDetail', $bankDetail);
    }

    /**
     * Show the form for editing the specified BankDetail.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $bankDetail = $this->bankDetailRepository->findWithoutFail($id);

        if (empty($bankDetail)) {
            Flash::error('Bank Detail not found');

            return redirect(route('bankDetails.index'));
        }

        return view('bank_details.edit')->with('bankDetail', $bankDetail);
    }

    /**
     * Update the specified BankDetail in storage.
     *
     * @param  int              $id
     * @param UpdateBankDetailRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateBankDetailRequest $request)
    {
        $bankDetail = $this->bankDetailRepository->findWithoutFail($id);

        if (empty($bankDetail)) {
            Flash::error('Bank Detail not found');

            return redirect(route('bankDetails.index'));
        }

        $bankDetail = $this->bankDetailRepository->update($request->all(), $id);

        Flash::success('Bank Detail updated successfully.');

        return redirect(route('bankDetails.index'));
    }

    /**
     * Remove the specified BankDetail from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $bankDetail = $this->bankDetailRepository->findWithoutFail($id);

        if (empty($bankDetail)) {
            Flash::error('Bank Detail not found');

            return redirect(route('bankDetails.index'));
        }

        $this->bankDetailRepository->delete($id);

        Flash::success('Bank Detail deleted successfully.');

        return redirect(route('bankDetails.index'));
    }
}

resources/views/bank_details/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Bank Detail
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'bankDetails.store']) !!}

                        @include('bank_details.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bank_details/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Bank Detail
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($bankDetail, ['route' => ['bankDetails.update', $bankDetail->id], 'method' => 'patch']) !!}

                        @include('bank_details.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/bank_details/fields.blade.php
<!-- Bank Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('bank_id', 'Bank Id:') !!}
    {!! Form::select('bank_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Applicant Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('applicant_id', 'Applicant Id:') !!}
    {!! Form::select('applicant_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Account Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('account_name', 'Account Name:') !!}
    {!! Form::text('account_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Account Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('account_number', 'Account Number:') !!}
    {!! Form::text('account_number', null, ['class' => 'form-control']) !!}
</div>

<!-- Sort Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('sort_code', 'Sort Code:') !!}
    {!! Form::text('sort_code', null, ['class' => 'form-control']) !!}
</div>

<!-- Bvn Field -->
<div class="form-group col-sm-6">
    {!! Form::label('bvn', 'Bvn:') !!}
    {!! Form::text('bvn', null, ['class' => 'form-control']) !!}
</div>

<!-- State Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('state_id', 'State Id:') !!}
    {!! Form::select('state_id', ], null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('bankDetails.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/bank_details/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Bank Details</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('bankDetails.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('bank_details.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/bank_details/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Bank Detail
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('bank_details.show_fields')
                    <a href="{!! route('bankDetails.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bank_details/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $bankDetail->id !!}</p>
</div>

<!-- Bank Id Field -->
<div class="form-group">
    {!! Form::label('bank_id', 'Bank Id:') !!}
    <p>{!! $bankDetail->bank_id !!}</p>
</div>

<!-- Applicant Id Field -->
<div class="form-group">
    {!! Form::label('applicant_id', 'Applicant Id:') !!}
    <p>{!! $bankDetail->applicant_id !!}</p>
</div>

<!-- Account Name Field -->
<div class="form-group">
    {!! Form::label('account_name', 'Account Name:') !!}
    <p>{!! $bankDetail->account_name !!}</p>
</div>

<!-- Account Number Field -->
<div class="form-group">
    {!! Form::label('account_number', 'Account Number:') !!}
    <p>{!! $bankDetail->account_number !!}</p>
</div>

<!-- Sort Code Field -->
<div class="form-group">
    {!! Form::label('sort_code', 'Sort Code:') !!}
    <p>{!! $bankDetail->sort_code !!}</p>
</div>

<!-- Bvn Field -->
<div class="form-group">
    {!! Form::label('bvn', 'Bvn:') !!}
    <p>{!! $bankDetail->bvn !!}</p>
</div>

<!-- State Id Field -->
<div class="form-group">
    {!! Form::label('state_id', 'State Id:') !!}
    <p>{!! $bankDetail->state_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $bankDetail->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $bankDetail->updated_at !!}</p>
</div>

resources/views/bank_details/table.blade.php
<table class="table table-responsive" id="bankDetails-table">
    <thead>
        <tr>
            <th>Bank Id</th>
        <th>Applicant Id</th>
        <th>Account Name</th>
        <th>Account Number</th>
        <th>Sort Code</th>
        <th>Bvn</th>
        <th>State Id</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($bankDetails as $bankDetail)
        <tr>
            <td>{!! $bankDetail->bank_id !!}</td>
            <td>{!! $bankDetail->applicant_id !!}</td>
            <td>{!! $bankDetail->account_name !!}</td>
            <td>{!! $bankDetail->account_number !!}</td>
            <td>{!! $bankDetail->sort_code !!}</td>
            <td>{!! $bankDetail->bvn !!}</td>
            <td>{!! $bankDetail->state_id !!}</td>
            <td>
                {!! Form::open(['route' => ['bankDetails.destroy', $bankDetail->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('bankDetails.show', [$bankDetail->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('bankDetails.edit', [$bankDetail->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>