routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::resource('api/application', 'ApplicationController');
//Route::resource('api/application/submit', 'ApplicationController@submit');

Auth::routes();
Route::get('/home', 'HomeController@index');

Route::resource('ipoCategories', 'IpoCategoryController');

Route::resource('applicationTypes', 'ApplicationTypeController');

Route::resource('applicationDetails', 'ApplicationDetailController');

Route::resource('applicants', 'ApplicantController');

Route::resource('corporateDetails', 'CorporateDetailController');

Route::resource('applicantDetails', 'ApplicantDetailController');

Route::resource('countries', 'CountryController');

Route::resource('states', 'StateController');

Route::resource('addresses', 'AddressController');

Route::resource('stockBrokerCompanies', 'StockBrokerCompanyController');

Route::resource('stockBrokers', 'StockBrokerController');

Route::resource('banks', 'BankController');

Route::resource('bankDetails', 'BankDetailController');

Route::resource('ipoRequests', 'IpoRequestController');

Route::resource('biddings', 'BiddingController');

Route::resource('ipoTypes', 'IpoTypeController');

Route::resource('partyTypes', 'PartyTypeController');

Route::resource('ipoDetails', 'IpoDetailController');

Route::resource('ipoProcesses', 'IpoProcessController');

Route::resource('allocations', 'AllocationController');

Route::resource('stockBrokerIpos', 'StockBrokerIpoController');

Route::resource('participants', 'ParticipantController');



Route::resource('partyResponses', 'PartyResponseController');

Route::resource('batches', 'BatchController');

Route::resource('batchContents', 'BatchContentController');

Route::resource('applicationApplicants', 'ApplicationApplicantController');







Route::resource('applicationSignatures', 'ApplicationSignatureController');

Route::resource('users', 'UserController');

Route::resource('serviceRequests', 'ServiceRequestController');

Route::resource('issuingHouses', 'IssuingHouseController');

Route::resource('issuingHouseStaffs', 'IssuingHouseStaffController');

Route::resource('registrars', 'RegistrarController');

Route::resource('registrarStaffs', 'RegistrarStaffController');

app/Models/ApplicationDetail.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="ApplicationDetail",
 *      required={"email", "ipo_category_id", "token", "application_type_id"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="email",
 *          description="email",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="ipo_category_id",
 *          description="ipo_category_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="token",
 *          description="token",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="application_type_id",
 *          description="application_type_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class ApplicationDetail extends Model
{
    use SoftDeletes;

    public $table = 'application_details';
    protected $dates = ['deleted_at'];


    public $fillable = [
        'email',
        'ipo_id',
        'token',
        'batched',
        'application_type_id'
    ];

    protected $hidden=["created_at","updated_at","deleted_at"];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'email' => 'string',
        'ipo_id' => 'integer',
        'token' => 'string',
        'batched'=>'boolean',
        'application_type_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'email' => 'required',
        'ipo_id' => 'required',
        'token' => 'required',
        'application_type_id' => 'required'
    ];

    public function applicants(){
        return $this->hasMany("App\Models\Applicant","application_id","id");
    }

    public function applicant_details(){
        return $this->hasMany("App\Models\ApplicantDetail","application_id","id");
    }

    public function address(){
        return $this->hasOne("App\Models\Address","application_id","id");
    }

    public function bank_detail(){
        return $this->hasOne("App\Models\BankDetail","application_id","id");
    }

    public function signatures(){
        return $this->hasMany("App\Models\ApplicationSignature","application_id","id");
    }

    public function corporate(){
        return $this->hasOne("App\Models\CorporateDetail","application_id","id");
    }

    public function ipo_request(){
        return $this->hasOne("App\Models\IpoRequest","application_id","id");
    }
    
}

app/Http/Controllers/ApplicationDetailController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateApplicationDetailRequest;
use App\Http\Requests\UpdateApplicationDetailRequest;
use App\Repositories\ApplicationDetailRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class ApplicationDetailController extends AppBaseController
{
    /** @var  ApplicationDetailRepository */
    private $applicationDetailRepository;

    public function __construct(ApplicationDetailRepository $applicationDetailRepo)
    {
        $this->applicationDetailRepository = $applicationDetailRepo;
    }

    /**
     * Display a listing of the ApplicationDetail.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->applicationDetailRepository->pushCriteria(new RequestCriteria($request));
        $applicationDetails = $this->applicationDetailRepository->all();

        return view('application_details.index')
            ->with('applicationDetails', $applicationDetails);
    }

    /**
     * Show the form for creating a new ApplicationDetail.
     *
     * @return Response
     */
    public function create()
    {
        return view('application_details.create');
    }

    /**
     * Store a newly created ApplicationDetail in storage.
     *
     * @param CreateApplicationDetailRequest $request
     *
     * @return Response
     */
    public function store(CreateApplicationDetailRequest $request)
    {
        $input = $request->all();

        $applicationDetail = $this->applicationDetailRepository->create($input);

        Flash::success('Application Detail saved successfully.');

        return redirect(route('applicationDetails.index'));
    }

    /**
     * Display the specified ApplicationDetail.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $applicationDetail = $this->applicationDetailRepository->findWithoutFail($id);

        if (empty($applicationDetail)) {
            Flash::error('Application Detail not found');

            return redirect(route('applicationDetails.index'));
        }

        return view('application_details.show')->with('applicationDetail', $applicationDetail);
    }

    /**
     * Show the form for editing the specified ApplicationDetail.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $applicationDetail = $this->applicationDetailRepository->findWithoutFail($id);

        if (empty($applicationDetail)) {
            Flash::error('Application Detail not found');

            return redirect(route('applicationDetails.index'));
        }

        return view('application_details.edit')->with('applicationDetail', $applicationDetail);
    }

    /**
     * Update the specified ApplicationDetail in storage.
     *
     * @param  int              $id
     * @param UpdateApplicationDetailRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateApplicationDetailRequest $request)
    {
        $applicationDetail = $this->applicationDetailRepository->findWithoutFail($id);

        if (empty($applicationDetail)) {
            Flash::error('Application Detail not found');

            return redirect(route('applicationDetails.index'));
        }

        $applicationDetail = $this->applicationDetailRepository->update($request->all(), $id);

        Flash::success('Application Detail updated successfully.');

        return redirect(route('applicationDetails.index'));
    }

    /**
     * Remove the specified ApplicationDetail from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $applicationDetail = $this->applicationDetailRepository->findWithoutFail($id);

        if (empty($applicationDetail)) {
            Flash::error('Application Detail not found');

            return redirect(route('applicationDetails.index'));
        }

        $this->applicationDetailRepository->delete($id);

        Flash::success('Application Detail deleted successfully.');

        return redirect(route('applicationDetails.index'));
    }
}

resources/views/application_details/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Application Detail
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'applicationDetails.store']) !!}

                        @include('application_details.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/application_details/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Application Detail
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($applicationDetail, ['route' => ['applicationDetails.update', $applicationDetail->id], 'method' => 'patch']) !!}

                        @include('application_details.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/application_details/fields.blade.php
<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Ipo Category Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ipo_category_id', 'Ipo Category Id:') !!}
    {!! Form::select('ipo_category_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Application Type Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('application_type_id', 'Application Type Id:') !!}
    {!! Form::select('application_type_id', [], null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('applicationDetails.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/application_details/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Application Details</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('applicationDetails.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('application_details.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/application_details/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Application Detail
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('application_details.show_fields')
                    <a href="{!! route('applicationDetails.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/application_details/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $applicationDetail->id !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $applicationDetail->email !!}</p>
</div>

<!-- Ipo Category Id Field -->
<div class="form-group">
    {!! Form::label('ipo_category_id', 'Ipo Category Id:') !!}
    <p>{!! $applicationDetail->ipo_category_id !!}</p>
</div>

<!-- Token Field -->
<div class="form-group">
    {!! Form::label('token', 'Token:') !!}
    <p>{!! $applicationDetail->token !!}</p>
</div>

<!-- Application Type Id Field -->
<div class="form-group">
    {!! Form::label('application_type_id', 'Application Type Id:') !!}
    <p>{!! $applicationDetail->application_type_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $applicationDetail->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $applicationDetail->updated_at !!}</p>
</div>

resources/views/application_details/table.blade.php
<table class="table table-responsive" id="applicationDetails-table">
    <thead>
        <tr>
            <th>Email</th>
        <th>Ipo Category Id</th>
        <th>Token</th>
        <th>Application Type Id</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($applicationDetails as $applicationDetail)
        <tr>
            <td>{!! $applicationDetail->email !!}</td>
            <td>{!! $applicationDetail->ipo_category_id !!}</td>
            <td>{!! $applicationDetail->token !!}</td>
            <td>{!! $applicationDetail->application_type_id !!}</td>
            <td>
                {!! Form::open(['route' => ['applicationDetails.destroy', $applicationDetail->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('applicationDetails.show', [$applicationDetail->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('applicationDetails.edit', [$applicationDetail->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>