routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::resource('api/application', 'ApplicationController');
//Route::resource('api/application/submit', 'ApplicationController@submit');

Auth::routes();
Route::get('/home', 'HomeController@index');

Route::resource('ipoCategories', 'IpoCategoryController');

Route::resource('applicationTypes', 'ApplicationTypeController');

Route::resource('applicationDetails', 'ApplicationDetailController');

Route::resource('applicants', 'ApplicantController');

Route::resource('corporateDetails', 'CorporateDetailController');

Route::resource('applicantDetails', 'ApplicantDetailController');

Route::resource('countries', 'CountryController');

Route::resource('states', 'StateController');

Route::resource('addresses', 'AddressController');

Route::resource('stockBrokerCompanies', 'StockBrokerCompanyController');

Route::resource('stockBrokers', 'StockBrokerController');

Route::resource('banks', 'BankController');

Route::resource('bankDetails', 'BankDetailController');

Route::resource('ipoRequests', 'IpoRequestController');

Route::resource('biddings', 'BiddingController');

Route::resource('ipoTypes', 'IpoTypeController');

Route::resource('partyTypes', 'PartyTypeController');

Route::resource('ipoDetails', 'IpoDetailController');

Route::resource('ipoProcesses', 'IpoProcessController');

Route::resource('allocations', 'AllocationController');

Route::resource('stockBrokerIpos', 'StockBrokerIpoController');

Route::resource('participants', 'ParticipantController');



Route::resource('partyResponses', 'PartyResponseController');

Route::resource('batches', 'BatchController');

Route::resource('batchContents', 'BatchContentController');

Route::resource('applicationApplicants', 'ApplicationApplicantController');







Route::resource('applicationSignatures', 'ApplicationSignatureController');

Route::resource('users', 'UserController');

Route::resource('serviceRequests', 'ServiceRequestController');

Route::resource('issuingHouses', 'IssuingHouseController');

Route::resource('issuingHouseStaffs', 'IssuingHouseStaffController');

Route::resource('registrars', 'RegistrarController');

Route::resource('registrarStaffs', 'RegistrarStaffController');

resources/views/party_responses/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Party Response
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'partyResponses.store']) !!}

                        @include('party_responses.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/party_responses/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Party Response
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($partyResponse, ['route' => ['partyResponses.update', $partyResponse->id], 'method' => 'patch']) !!}

                        @include('party_responses.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/party_responses/fields.blade.php
<!-- Ipo Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ipo_id', 'Ipo Id:') !!}
    {!! Form::select('ipo_id', ], null, ['class' => 'form-control']) !!}
</div>

<!-- Party Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('party_id', 'Party Id:') !!}
    {!! Form::select('party_id', ], null, ['class' => 'form-control']) !!}
</div>

<!-- Participant Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('participant_id', 'Participant Id:') !!}
    {!! Form::select('participant_id', ], null, ['class' => 'form-control']) !!}
</div>

<!-- Logo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('logo', 'Logo:') !!}
    {!! Form::file('logo') !!}
</div>
<div class="clearfix"></div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('partyResponses.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/party_responses/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Party Responses</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('partyResponses.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('party_responses.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/party_responses/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Party Response
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('party_responses.show_fields')
                    <a href="{!! route('partyResponses.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/party_responses/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $partyResponse->id !!}</p>
</div>

<!-- Ipo Id Field -->
<div class="form-group">
    {!! Form::label('ipo_id', 'Ipo Id:') !!}
    <p>{!! $partyResponse->ipo_id !!}</p>
</div>

<!-- Party Id Field -->
<div class="form-group">
    {!! Form::label('party_id', 'Party Id:') !!}
    <p>{!! $partyResponse->party_id !!}</p>
</div>

<!-- Participant Id Field -->
<div class="form-group">
    {!! Form::label('participant_id', 'Participant Id:') !!}
    <p>{!! $partyResponse->participant_id !!}</p>
</div>

<!-- Logo Field -->
<div class="form-group">
    {!! Form::label('logo', 'Logo:') !!}
    <p>{!! $partyResponse->logo !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $partyResponse->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $partyResponse->updated_at !!}</p>
</div>

resources/views/party_responses/table.blade.php
<table class="table table-responsive" id="partyResponses-table">
    <thead>
        <tr>
            <th>Ipo Id</th>
        <th>Party Id</th>
        <th>Participant Id</th>
        <th>Logo</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($partyResponses as $partyResponse)
        <tr>
            <td>{!! $partyResponse->ipo_id !!}</td>
            <td>{!! $partyResponse->party_id !!}</td>
            <td>{!! $partyResponse->participant_id !!}</td>
            <td>{!! $partyResponse->logo !!}</td>
            <td>
                {!! Form::open(['route' => ['partyResponses.destroy', $partyResponse->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('partyResponses.show', [$partyResponse->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('partyResponses.edit', [$partyResponse->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>